name: Update IP Ranges

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-ip-ranges:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install uv
        cd crawler
        uv sync --no-dev

    - name: Run Update IP ranges
      id: build
      run: |
        source crawler/.venv/bin/activate
        mkdir -p json txt csv
        cd json
        python3 ../crawler/src/cloud_ip_ranges.py --add-env-statistics --only-if-changed --logfile ../run.log --output-format json csv txt
        # Read log file and encode newlines
        LOG_CONTENT=$(cat ../run.log | sed 's/$/\\n/' | tr -d '\n')
        echo "log_content=${LOG_CONTENT}" >> $GITHUB_OUTPUT
        mv *.txt ../txt
        mv *.csv ../csv

    - name: Add and commit
      uses: EndBug/add-and-commit@v9
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'json txt csv'

        # The name of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_name: Auto Update Bot

        # The email of the user that will be displayed as the author of the commit.
        # Default: depends on the default_author input
        author_email: bot@github.com

        # The message for the commit.
        # Default: 'Commit from GitHub Actions (name of the workflow)'
        message: |
          Updated ${{ steps.vars.outputs.sources_updated }} (IPv4: ${{ steps.vars.outputs.total_ipv4 }}, IPv6: ${{ steps.vars.outputs.total_ipv6 }})

          ${{ steps.build.outputs.log_content }}"
